import Link from "next/link";
import styles from "./CIBILGuide.module.css";
import { getAllSettings } from "@/lib/db";

export const dynamic = "force-dynamic";

export const metadata = {
  title: "CIBIL Score Guide | Nilesh Kute",
  description: "Learn what CIBIL score is, why it matters for home loans, what is a good score, and how to improve your credit score.",
};

const sections = [
  {
    icon: "📊",
    title: "What is CIBIL Score?",
    content: "CIBIL Score (also called Credit Score) is a 3-digit numeric summary of your credit history, ranging from 300 to 900. It is generated by TransUnion CIBIL based on your credit behaviour — how you manage loans, credit cards, and repayments. It is one of the most important factors lenders check before approving any loan.",
  },
  {
    icon: "🏦",
    title: "Why CIBIL Score Matters for Home Loans",
    content: "When you apply for a home loan, lenders pull your credit report to assess your creditworthiness. A strong CIBIL score indicates that you are a responsible borrower. A weak score can lead to loan rejection or higher interest rates. Most lenders have minimum CIBIL score requirements for different loan types.",
  },
  {
    icon: "⭐",
    title: "What is Considered a Good Score?",
    content: `Score ranges and what they generally indicate:
• 750 – 900: Excellent — Best chances of approval with competitive terms
• 700 – 749: Good — Good approval chances
• 650 – 699: Fair — Approval possible but terms may be stricter
• 600 – 649: Below Average — Approval may be difficult
• Below 600: Poor — Very difficult to get loan approval

Note: Different lenders may have different criteria.`,
  },
  {
    icon: "📈",
    title: "How to Improve Your CIBIL Score",
    content: `• Pay all EMIs and credit card dues on time — even a single missed payment can impact your score significantly.
• Keep your credit card utilization below 30% of the limit.
• Avoid multiple loan or credit card applications in a short period.
• Maintain a healthy mix of secured (home loan, car loan) and unsecured (personal loan, credit card) credit.
• Regularly check your credit report for errors and dispute any inaccuracies.
• If you have no credit history, consider starting with a secured credit card.`,
  },
  {
    icon: "⚙️",
    title: "Factors That Affect Your CIBIL Score",
    content: `• Payment history (most significant factor)
• Credit utilization ratio
• Age of credit history (older accounts help)
• Number of recent credit enquiries (hard pulls)
• Credit mix (types of credit you hold)
• Outstanding debt and number of accounts`,
  },
  {
    icon: "❌",
    title: "Why Loans Get Rejected Due to Credit Profile",
    content: `• CIBIL score below lender's minimum threshold
• History of missed or delayed EMI payments
• High credit card utilization
• Multiple recent loan applications (seen as credit hungry behaviour)
• Accounts written off or settled (which shows on your report)
• Guarantor on a defaulted loan`,
  },
  {
    icon: "✅",
    title: "Maintaining Healthy Credit Behaviour",
    content: `• Set up auto-pay for all your EMIs to never miss a payment.
• Review your CIBIL report at least once a year.
• Do not close old credit accounts unless necessary.
• Avoid being a guarantor unless you are confident the borrower will repay.
• Space out your loan applications — avoid applying for multiple products simultaneously.`,
  },
];

export default function CIBILGuidePage() {
  const settings = getAllSettings();
  const whatsapp = settings.whatsapp || "918356008675";

  return (
    <div className={styles.main}>
      <section className={styles.hero}>
        <div className="container text-center">
          <h1 className={styles.title}>CIBIL Score Guide</h1>
          <p className={styles.subtitle}>Everything you need to know about your credit score and how it impacts your home loan.</p>
        </div>
      </section>

      <section className={styles.contentSection}>
        <div className="container">
          <div className={styles.scoreBar}>
            <div className={styles.scoreBand} style={{ background: "#ef4444", flex: 1 }}>
              <span>Poor</span><small>&lt; 600</small>
            </div>
            <div className={styles.scoreBand} style={{ background: "#f97316", flex: 1 }}>
              <span>Below Avg</span><small>600–649</small>
            </div>
            <div className={styles.scoreBand} style={{ background: "#eab308", flex: 1 }}>
              <span>Fair</span><small>650–699</small>
            </div>
            <div className={styles.scoreBand} style={{ background: "#22c55e", flex: 1 }}>
              <span>Good</span><small>700–749</small>
            </div>
            <div className={styles.scoreBand} style={{ background: "#16a34a", flex: 1.5 }}>
              <span>Excellent</span><small>750–900</small>
            </div>
          </div>

          <div className={styles.sections}>
            {sections.map((s, i) => (
              <div key={i} className={styles.sectionCard}>
                <div className={styles.sectionIcon}>{s.icon}</div>
                <div className={styles.sectionContent}>
                  <h2 className={styles.sectionTitle}>{s.title}</h2>
                  <p className={styles.sectionText} style={{ whiteSpace: "pre-line" }}>{s.content}</p>
                </div>
              </div>
            ))}
          </div>

          <div className={styles.ctaBanner}>
            <h3>Need help understanding your loan eligibility?</h3>
            <p>Get a free, no-obligation consultation with Nilesh Kute.</p>
            <div className={styles.ctaButtons}>
              <a href="/apply" className="btn">Get Free Consultation</a>
              <a href={`https://wa.me/${whatsapp}`} target="_blank" rel="noreferrer" className="btn-secondary">WhatsApp Now</a>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
